/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gamenftrewardSol from "./Gamenftreward.sol";
export type { gamenftrewardSol };
export type { IHederaTokenService } from "./IHederaTokenService";
export type { LeaderboardManager } from "./LeaderboardManager";
