/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LeaderboardManager {
  export type PlayerStatsStruct = {
    playerAddress: AddressLike;
    highestScore: BigNumberish;
    totalKills: BigNumberish;
    totalSessions: BigNumberish;
    lastUpdated: BigNumberish;
    exists: boolean;
  };

  export type PlayerStatsStructOutput = [
    playerAddress: string,
    highestScore: bigint,
    totalKills: bigint,
    totalSessions: bigint,
    lastUpdated: bigint,
    exists: boolean
  ] & {
    playerAddress: string;
    highestScore: bigint;
    totalKills: bigint;
    totalSessions: bigint;
    lastUpdated: bigint;
    exists: boolean;
  };
}

export interface LeaderboardManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "gameServer"
      | "getPlayerRank"
      | "getPlayerStats"
      | "getTop10"
      | "getTopPlayersAddresses"
      | "owner"
      | "players"
      | "setGameServer"
      | "topPlayers"
      | "totalPlayers"
      | "transferOwnership"
      | "updatePlayerScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameServerUpdated"
      | "NewTopPlayer"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "gameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getTop10", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTopPlayersAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlayerScore",
    values: [AddressLike, BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "gameServer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTop10", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTopPlayersAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlayerScore",
    data: BytesLike
  ): Result;
}

export namespace GameServerUpdatedEvent {
  export type InputTuple = [oldServer: AddressLike, newServer: AddressLike];
  export type OutputTuple = [oldServer: string, newServer: string];
  export interface OutputObject {
    oldServer: string;
    newServer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewTopPlayerEvent {
  export type InputTuple = [
    player: AddressLike,
    rank: BigNumberish,
    score: BigNumberish
  ];
  export type OutputTuple = [player: string, rank: bigint, score: bigint];
  export interface OutputObject {
    player: string;
    rank: bigint;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    newHighScore: BigNumberish,
    sessionScore: BigNumberish,
    hcsMessageId: string
  ];
  export type OutputTuple = [
    player: string,
    newHighScore: bigint,
    sessionScore: bigint,
    hcsMessageId: string
  ];
  export interface OutputObject {
    player: string;
    newHighScore: bigint;
    sessionScore: bigint;
    hcsMessageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LeaderboardManager extends BaseContract {
  connect(runner?: ContractRunner | null): LeaderboardManager;
  waitForDeployment(): Promise<this>;

  interface: LeaderboardManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  gameServer: TypedContractMethod<[], [string], "view">;

  getPlayerRank: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [LeaderboardManager.PlayerStatsStructOutput],
    "view"
  >;

  getTop10: TypedContractMethod<
    [],
    [LeaderboardManager.PlayerStatsStructOutput[]],
    "view"
  >;

  getTopPlayersAddresses: TypedContractMethod<[], [string[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  players: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  setGameServer: TypedContractMethod<
    [newGameServer: AddressLike],
    [void],
    "nonpayable"
  >;

  topPlayers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalPlayers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlayerScore: TypedContractMethod<
    [
      player: AddressLike,
      sessionScore: BigNumberish,
      kills: BigNumberish,
      hcsMessageId: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "gameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerRank"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [LeaderboardManager.PlayerStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTop10"
  ): TypedContractMethod<
    [],
    [LeaderboardManager.PlayerStatsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopPlayersAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setGameServer"
  ): TypedContractMethod<[newGameServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "topPlayers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlayerScore"
  ): TypedContractMethod<
    [
      player: AddressLike,
      sessionScore: BigNumberish,
      kills: BigNumberish,
      hcsMessageId: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameServerUpdated"
  ): TypedContractEvent<
    GameServerUpdatedEvent.InputTuple,
    GameServerUpdatedEvent.OutputTuple,
    GameServerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NewTopPlayer"
  ): TypedContractEvent<
    NewTopPlayerEvent.InputTuple,
    NewTopPlayerEvent.OutputTuple,
    NewTopPlayerEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "GameServerUpdated(address,address)": TypedContractEvent<
      GameServerUpdatedEvent.InputTuple,
      GameServerUpdatedEvent.OutputTuple,
      GameServerUpdatedEvent.OutputObject
    >;
    GameServerUpdated: TypedContractEvent<
      GameServerUpdatedEvent.InputTuple,
      GameServerUpdatedEvent.OutputTuple,
      GameServerUpdatedEvent.OutputObject
    >;

    "NewTopPlayer(address,uint256,uint256)": TypedContractEvent<
      NewTopPlayerEvent.InputTuple,
      NewTopPlayerEvent.OutputTuple,
      NewTopPlayerEvent.OutputObject
    >;
    NewTopPlayer: TypedContractEvent<
      NewTopPlayerEvent.InputTuple,
      NewTopPlayerEvent.OutputTuple,
      NewTopPlayerEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256,uint256,string)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
