/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LeaderboardManager {
  export type LeaderboardEntryStruct = {
    rank: BigNumberish;
    player: AddressLike;
    highestScore: BigNumberish;
    totalKills: BigNumberish;
    totalSessions: BigNumberish;
    averageAccuracy: BigNumberish;
    lastUpdated: BigNumberish;
  };

  export type LeaderboardEntryStructOutput = [
    rank: bigint,
    player: string,
    highestScore: bigint,
    totalKills: bigint,
    totalSessions: bigint,
    averageAccuracy: bigint,
    lastUpdated: bigint
  ] & {
    rank: bigint;
    player: string;
    highestScore: bigint;
    totalKills: bigint;
    totalSessions: bigint;
    averageAccuracy: bigint;
    lastUpdated: bigint;
  };
}

export interface LeaderboardManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_KILLS"
      | "MAX_SCORE"
      | "gameServer"
      | "getGlobalStats"
      | "getPlayerRank"
      | "getPlayerStats"
      | "getTop10"
      | "owner"
      | "players"
      | "setGameServer"
      | "submitSession"
      | "topPlayers"
      | "totalPlayers"
      | "totalSessions"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvalidSessionRejected"
      | "LeaderboardUpdated"
      | "NewHighScore"
      | "SessionSubmitted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_KILLS", values?: undefined): string;
  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerRank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getTop10", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSession",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "topPlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSessions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_KILLS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameServer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTop10", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace InvalidSessionRejectedEvent {
  export type InputTuple = [player: AddressLike, reason: string];
  export type OutputTuple = [player: string, reason: string];
  export interface OutputObject {
    player: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [
    blockNumber: BigNumberish,
    timestamp: BigNumberish,
    leaderboard: LeaderboardManager.LeaderboardEntryStruct[]
  ];
  export type OutputTuple = [
    blockNumber: bigint,
    timestamp: bigint,
    leaderboard: LeaderboardManager.LeaderboardEntryStructOutput[]
  ];
  export interface OutputObject {
    blockNumber: bigint;
    timestamp: bigint;
    leaderboard: LeaderboardManager.LeaderboardEntryStructOutput[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewHighScoreEvent {
  export type InputTuple = [
    player: AddressLike,
    oldScore: BigNumberish,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    oldScore: bigint,
    newScore: bigint
  ];
  export interface OutputObject {
    player: string;
    oldScore: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionSubmittedEvent {
  export type InputTuple = [
    player: AddressLike,
    score: BigNumberish,
    kills: BigNumberish,
    accuracy: BigNumberish,
    timeSurvived: BigNumberish,
    hcsMessageId: string
  ];
  export type OutputTuple = [
    player: string,
    score: bigint,
    kills: bigint,
    accuracy: bigint,
    timeSurvived: bigint,
    hcsMessageId: string
  ];
  export interface OutputObject {
    player: string;
    score: bigint;
    kills: bigint;
    accuracy: bigint;
    timeSurvived: bigint;
    hcsMessageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LeaderboardManager extends BaseContract {
  connect(runner?: ContractRunner | null): LeaderboardManager;
  waitForDeployment(): Promise<this>;

  interface: LeaderboardManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_KILLS: TypedContractMethod<[], [bigint], "view">;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  gameServer: TypedContractMethod<[], [string], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string] & {
        _totalPlayers: bigint;
        _totalSessions: bigint;
        highestScoreEver: bigint;
        topPlayer: string;
      }
    ],
    "view"
  >;

  getPlayerRank: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        averageAccuracy: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getTop10: TypedContractMethod<
    [],
    [LeaderboardManager.LeaderboardEntryStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  players: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        totalAccuracy: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  setGameServer: TypedContractMethod<
    [newServer: AddressLike],
    [void],
    "nonpayable"
  >;

  submitSession: TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      hcsMessageId: string
    ],
    [void],
    "nonpayable"
  >;

  topPlayers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  totalPlayers: TypedContractMethod<[], [bigint], "view">;

  totalSessions: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_KILLS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, string] & {
        _totalPlayers: bigint;
        _totalSessions: bigint;
        highestScoreEver: bigint;
        topPlayer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerRank"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        averageAccuracy: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTop10"
  ): TypedContractMethod<
    [],
    [LeaderboardManager.LeaderboardEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        playerAddress: string;
        highestScore: bigint;
        totalKills: bigint;
        totalSessions: bigint;
        totalAccuracy: bigint;
        lastUpdated: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setGameServer"
  ): TypedContractMethod<[newServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitSession"
  ): TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      hcsMessageId: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "topPlayers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSessions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "InvalidSessionRejected"
  ): TypedContractEvent<
    InvalidSessionRejectedEvent.InputTuple,
    InvalidSessionRejectedEvent.OutputTuple,
    InvalidSessionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NewHighScore"
  ): TypedContractEvent<
    NewHighScoreEvent.InputTuple,
    NewHighScoreEvent.OutputTuple,
    NewHighScoreEvent.OutputObject
  >;
  getEvent(
    key: "SessionSubmitted"
  ): TypedContractEvent<
    SessionSubmittedEvent.InputTuple,
    SessionSubmittedEvent.OutputTuple,
    SessionSubmittedEvent.OutputObject
  >;

  filters: {
    "InvalidSessionRejected(address,string)": TypedContractEvent<
      InvalidSessionRejectedEvent.InputTuple,
      InvalidSessionRejectedEvent.OutputTuple,
      InvalidSessionRejectedEvent.OutputObject
    >;
    InvalidSessionRejected: TypedContractEvent<
      InvalidSessionRejectedEvent.InputTuple,
      InvalidSessionRejectedEvent.OutputTuple,
      InvalidSessionRejectedEvent.OutputObject
    >;

    "LeaderboardUpdated(uint256,uint256,tuple[10])": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "NewHighScore(address,uint256,uint256)": TypedContractEvent<
      NewHighScoreEvent.InputTuple,
      NewHighScoreEvent.OutputTuple,
      NewHighScoreEvent.OutputObject
    >;
    NewHighScore: TypedContractEvent<
      NewHighScoreEvent.InputTuple,
      NewHighScoreEvent.OutputTuple,
      NewHighScoreEvent.OutputObject
    >;

    "SessionSubmitted(address,uint256,uint256,uint256,uint256,string)": TypedContractEvent<
      SessionSubmittedEvent.InputTuple,
      SessionSubmittedEvent.OutputTuple,
      SessionSubmittedEvent.OutputObject
    >;
    SessionSubmitted: TypedContractEvent<
      SessionSubmittedEvent.InputTuple,
      SessionSubmittedEvent.OutputTuple,
      SessionSubmittedEvent.OutputObject
    >;
  };
}
