/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HederaGameRewardNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "checkIsCollection"
      | "checkSignature"
      | "createNFTCollection"
      | "eip712Domain"
      | "flagSession"
      | "gameServer"
      | "getDomainSeparator"
      | "getPlayerNFTCount"
      | "getRoleAdmin"
      | "getTypehash"
      | "grantRole"
      | "hasRole"
      | "isCollection"
      | "isSessionFlagged"
      | "isSessionUsed"
      | "lastCreatedCollection"
      | "mintAndTransfer"
      | "mintBatchToTreasury"
      | "mintNFTToTreasury"
      | "owner"
      | "playerNFTCount"
      | "renounceOwnership"
      | "renounceRole"
      | "requestReward"
      | "revokeRole"
      | "sessionFlagged"
      | "sessionUsed"
      | "setGameServer"
      | "setOperator"
      | "supportsInterface"
      | "transferOwnership"
      | "verifySession"
      | "verifySessionAndMintReward"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EIP712DomainChanged"
      | "GameServerUpdated"
      | "NFTCollectionCreated"
      | "NFTMinted"
      | "NFTRewardMinted"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "RewardRequested"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SessionFlagged"
      | "SessionVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkIsCollection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createNFTCollection",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flagSession",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "gameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerNFTCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTypehash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCollection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSessionFlagged",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSessionUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastCreatedCollection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintAndTransfer",
    values: [AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchToTreasury",
    values: [AddressLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintNFTToTreasury",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerNFTCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReward",
    values: [BytesLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionFlagged",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGameServer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySession",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySessionAndMintReward",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIsCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createNFTCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flagSession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameServer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerNFTCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTypehash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSessionFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSessionUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCreatedCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAndTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintNFTToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerNFTCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sessionFlagged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGameServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySession",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySessionAndMintReward",
    data: BytesLike
  ): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameServerUpdatedEvent {
  export type InputTuple = [
    previousServer: AddressLike,
    newServer: AddressLike
  ];
  export type OutputTuple = [previousServer: string, newServer: string];
  export interface OutputObject {
    previousServer: string;
    newServer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTCollectionCreatedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    name: string,
    symbol: string,
    treasury: AddressLike
  ];
  export type OutputTuple = [
    tokenAddress: string,
    name: string,
    symbol: string,
    treasury: string
  ];
  export interface OutputObject {
    tokenAddress: string;
    name: string;
    symbol: string;
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTMintedEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    serial: BigNumberish,
    mintedTo: AddressLike,
    metadataURI: string
  ];
  export type OutputTuple = [
    tokenAddress: string,
    serial: bigint,
    mintedTo: string,
    metadataURI: string
  ];
  export interface OutputObject {
    tokenAddress: string;
    serial: bigint;
    mintedTo: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRewardMintedEvent {
  export type InputTuple = [
    sessionHash: BytesLike,
    player: AddressLike,
    tokenAddress: AddressLike,
    serial: BigNumberish,
    score: BigNumberish
  ];
  export type OutputTuple = [
    sessionHash: string,
    player: string,
    tokenAddress: string,
    serial: bigint,
    score: bigint
  ];
  export interface OutputObject {
    sessionHash: string;
    player: string;
    tokenAddress: string;
    serial: bigint;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [
    previousOperator: AddressLike,
    newOperator: AddressLike
  ];
  export type OutputTuple = [previousOperator: string, newOperator: string];
  export interface OutputObject {
    previousOperator: string;
    newOperator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardRequestedEvent {
  export type InputTuple = [
    sessionHash: BytesLike,
    player: AddressLike,
    rewardType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sessionHash: string,
    player: string,
    rewardType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sessionHash: string;
    player: string;
    rewardType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionFlaggedEvent {
  export type InputTuple = [
    sessionHash: BytesLike,
    player: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sessionHash: string,
    player: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sessionHash: string;
    player: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionVerifiedEvent {
  export type InputTuple = [
    sessionHash: BytesLike,
    player: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sessionHash: string,
    player: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sessionHash: string;
    player: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HederaGameRewardNFT extends BaseContract {
  connect(runner?: ContractRunner | null): HederaGameRewardNFT;
  waitForDeployment(): Promise<this>;

  interface: HederaGameRewardNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  checkIsCollection: TypedContractMethod<
    [tokenAddr: AddressLike],
    [boolean],
    "view"
  >;

  checkSignature: TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [
      [string, boolean] & {
        recoveredSigner: string;
        matchesGameServer: boolean;
      }
    ],
    "view"
  >;

  createNFTCollection: TypedContractMethod<
    [name: string, symbol: string, autoRenewPeriod: BigNumberish],
    [string],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  flagSession: TypedContractMethod<
    [sessionHash: BytesLike, player: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  gameServer: TypedContractMethod<[], [string], "view">;

  getDomainSeparator: TypedContractMethod<[], [string], "view">;

  getPlayerNFTCount: TypedContractMethod<
    [player: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTypehash: TypedContractMethod<[], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isCollection: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isSessionFlagged: TypedContractMethod<
    [sessionHash: BytesLike],
    [boolean],
    "view"
  >;

  isSessionUsed: TypedContractMethod<
    [sessionHash: BytesLike],
    [boolean],
    "view"
  >;

  lastCreatedCollection: TypedContractMethod<[], [string], "view">;

  mintAndTransfer: TypedContractMethod<
    [tokenAddr: AddressLike, recipient: AddressLike, metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  mintBatchToTreasury: TypedContractMethod<
    [tokenAddr: AddressLike, metadataURIs: string[]],
    [bigint[]],
    "nonpayable"
  >;

  mintNFTToTreasury: TypedContractMethod<
    [tokenAddr: AddressLike, metadataURI: string],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerNFTCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestReward: TypedContractMethod<
    [sessionHash: BytesLike, player: AddressLike, rewardType: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sessionFlagged: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  sessionUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  setGameServer: TypedContractMethod<
    [newServer: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [newOperator: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifySession: TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [[string, boolean] & { sessionHash: string; verified: boolean }],
    "nonpayable"
  >;

  verifySessionAndMintReward: TypedContractMethod<
    [
      tokenAddr: AddressLike,
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike,
      metadataURI: string
    ],
    [
      [string, boolean, bigint] & {
        sessionHash: string;
        verified: boolean;
        serial: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkIsCollection"
  ): TypedContractMethod<[tokenAddr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkSignature"
  ): TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [
      [string, boolean] & {
        recoveredSigner: string;
        matchesGameServer: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createNFTCollection"
  ): TypedContractMethod<
    [name: string, symbol: string, autoRenewPeriod: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "flagSession"
  ): TypedContractMethod<
    [sessionHash: BytesLike, player: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDomainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerNFTCount"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTypehash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCollection"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSessionFlagged"
  ): TypedContractMethod<[sessionHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSessionUsed"
  ): TypedContractMethod<[sessionHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastCreatedCollection"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintAndTransfer"
  ): TypedContractMethod<
    [tokenAddr: AddressLike, recipient: AddressLike, metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintBatchToTreasury"
  ): TypedContractMethod<
    [tokenAddr: AddressLike, metadataURIs: string[]],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintNFTToTreasury"
  ): TypedContractMethod<
    [tokenAddr: AddressLike, metadataURI: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerNFTCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestReward"
  ): TypedContractMethod<
    [sessionHash: BytesLike, player: AddressLike, rewardType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sessionFlagged"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sessionUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setGameServer"
  ): TypedContractMethod<[newServer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[newOperator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifySession"
  ): TypedContractMethod<
    [
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [[string, boolean] & { sessionHash: string; verified: boolean }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifySessionAndMintReward"
  ): TypedContractMethod<
    [
      tokenAddr: AddressLike,
      player: AddressLike,
      score: BigNumberish,
      kills: BigNumberish,
      accuracy: BigNumberish,
      timeSurvived: BigNumberish,
      timestamp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike,
      metadataURI: string
    ],
    [
      [string, boolean, bigint] & {
        sessionHash: string;
        verified: boolean;
        serial: bigint;
      }
    ],
    "nonpayable"
  >;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "GameServerUpdated"
  ): TypedContractEvent<
    GameServerUpdatedEvent.InputTuple,
    GameServerUpdatedEvent.OutputTuple,
    GameServerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTCollectionCreated"
  ): TypedContractEvent<
    NFTCollectionCreatedEvent.InputTuple,
    NFTCollectionCreatedEvent.OutputTuple,
    NFTCollectionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "NFTMinted"
  ): TypedContractEvent<
    NFTMintedEvent.InputTuple,
    NFTMintedEvent.OutputTuple,
    NFTMintedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRewardMinted"
  ): TypedContractEvent<
    NFTRewardMintedEvent.InputTuple,
    NFTRewardMintedEvent.OutputTuple,
    NFTRewardMintedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardRequested"
  ): TypedContractEvent<
    RewardRequestedEvent.InputTuple,
    RewardRequestedEvent.OutputTuple,
    RewardRequestedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SessionFlagged"
  ): TypedContractEvent<
    SessionFlaggedEvent.InputTuple,
    SessionFlaggedEvent.OutputTuple,
    SessionFlaggedEvent.OutputObject
  >;
  getEvent(
    key: "SessionVerified"
  ): TypedContractEvent<
    SessionVerifiedEvent.InputTuple,
    SessionVerifiedEvent.OutputTuple,
    SessionVerifiedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "GameServerUpdated(address,address)": TypedContractEvent<
      GameServerUpdatedEvent.InputTuple,
      GameServerUpdatedEvent.OutputTuple,
      GameServerUpdatedEvent.OutputObject
    >;
    GameServerUpdated: TypedContractEvent<
      GameServerUpdatedEvent.InputTuple,
      GameServerUpdatedEvent.OutputTuple,
      GameServerUpdatedEvent.OutputObject
    >;

    "NFTCollectionCreated(address,string,string,address)": TypedContractEvent<
      NFTCollectionCreatedEvent.InputTuple,
      NFTCollectionCreatedEvent.OutputTuple,
      NFTCollectionCreatedEvent.OutputObject
    >;
    NFTCollectionCreated: TypedContractEvent<
      NFTCollectionCreatedEvent.InputTuple,
      NFTCollectionCreatedEvent.OutputTuple,
      NFTCollectionCreatedEvent.OutputObject
    >;

    "NFTMinted(address,int64,address,string)": TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;
    NFTMinted: TypedContractEvent<
      NFTMintedEvent.InputTuple,
      NFTMintedEvent.OutputTuple,
      NFTMintedEvent.OutputObject
    >;

    "NFTRewardMinted(bytes32,address,address,int64,uint256)": TypedContractEvent<
      NFTRewardMintedEvent.InputTuple,
      NFTRewardMintedEvent.OutputTuple,
      NFTRewardMintedEvent.OutputObject
    >;
    NFTRewardMinted: TypedContractEvent<
      NFTRewardMintedEvent.InputTuple,
      NFTRewardMintedEvent.OutputTuple,
      NFTRewardMintedEvent.OutputObject
    >;

    "OperatorUpdated(address,address)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardRequested(bytes32,address,string,uint256)": TypedContractEvent<
      RewardRequestedEvent.InputTuple,
      RewardRequestedEvent.OutputTuple,
      RewardRequestedEvent.OutputObject
    >;
    RewardRequested: TypedContractEvent<
      RewardRequestedEvent.InputTuple,
      RewardRequestedEvent.OutputTuple,
      RewardRequestedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SessionFlagged(bytes32,address,string,uint256)": TypedContractEvent<
      SessionFlaggedEvent.InputTuple,
      SessionFlaggedEvent.OutputTuple,
      SessionFlaggedEvent.OutputObject
    >;
    SessionFlagged: TypedContractEvent<
      SessionFlaggedEvent.InputTuple,
      SessionFlaggedEvent.OutputTuple,
      SessionFlaggedEvent.OutputObject
    >;

    "SessionVerified(bytes32,address,uint256)": TypedContractEvent<
      SessionVerifiedEvent.InputTuple,
      SessionVerifiedEvent.OutputTuple,
      SessionVerifiedEvent.OutputObject
    >;
    SessionVerified: TypedContractEvent<
      SessionVerifiedEvent.InputTuple,
      SessionVerifiedEvent.OutputTuple,
      SessionVerifiedEvent.OutputObject
    >;
  };
}
