/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gamenftrewardSol from "./Gamenftreward.sol";
export { IHederaTokenService__factory } from "./IHederaTokenService__factory";
export { LeaderboardManager__factory } from "./LeaderboardManager__factory";
